let trends = [
  {id:'agentische-ki',category:'KI',title:'Agentische KI',symbol:'✦',relevance:96,date:'20.08.2026',description:'KI-Agenten übernehmen mehrstufige Abläufe statt nur einzelne Prompts.',insight:'Unternehmen entwickeln digitale Prozessketten, in denen spezialisierte Agenten Aufgaben planen, ausführen und prüfen. Entscheidend werden Governance, Rechteverwaltung und menschliche Kontrolle.',stage:'Beschleunigung',horizon:'Jetzt',source:'Google Cloud: AI Agent Trends 2026',sourceUrl:'https://cloud.google.com/resources/content/ai-agent-trends-2026'},
  {id:'physical-ai',category:'KI',title:'Physical AI',symbol:'⌁',relevance:92,date:'29.01.2026',description:'KI verlässt den Bildschirm und steuert Roboter in realen Umgebungen.',insight:'Allzweckroboter und verkörperte KI verbinden Wahrnehmung, Planung und Bewegung. Das eröffnet neue Anwendungen in Logistik, Pflege und Produktion.',stage:'Wachstum',horizon:'2–5 Jahre',source:'IEEE: Technology Predictions 2026',sourceUrl:'https://www.computer.org/resources/2026-tech-predictions'},
  {id:'intent-interfaces',category:'KI',title:'Natural Intent Interfaces',symbol:'≈',relevance:88,date:'29.01.2026',description:'Natürliche Sprache und Kontext ersetzen starre Klickpfade.',insight:'Software orientiert sich stärker am gewünschten Ergebnis. Sprache, Gesten und multimodale Eingaben werden zu einer gemeinsamen Bedienebene.',stage:'Beschleunigung',horizon:'Jetzt',source:'IEEE: Technology Predictions 2026',sourceUrl:'https://www.computer.org/press-room/2026-tech-predictions'},
  {id:'spatial-computing',category:'Technologie',title:'Spatial Computing',symbol:'◇',relevance:86,date:'29.01.2026',description:'Digitale Informationen werden räumlich und kontextbezogen nutzbar.',insight:'XR, Edge Computing und räumliche Intelligenz wachsen zusammen. Relevante Anwendungen entstehen in Planung, Training, Medizin und industrieller Wartung.',stage:'Wachstum',horizon:'1–3 Jahre',source:'IEEE: Technology Predictions 2026',sourceUrl:'https://ieeecs-media.computer.org/media/tech-news/tech-predictions-report-2026.pdf'},
  {id:'quantum-resilience',category:'Technologie',title:'Quantum Resilience',symbol:'◈',relevance:84,date:'05.05.2026',description:'Organisationen bereiten kritische Systeme auf Quantenrisiken vor.',insight:'Quantencomputing wird zur Infrastrukturfrage. Inventare kryptografischer Abhängigkeiten und migrationsfähige Sicherheitsarchitekturen gewinnen an Dringlichkeit.',stage:'Frühphase',horizon:'3–7 Jahre',source:'Technology Trends Report – März 2026',sourceUrl:'https://www.gov.pl/web/national-institute-of-telecommunications/the-future-already-here-just-not-everywhere'},
  {id:'digitale-souveraenitaet',category:'Business',title:'Digitale Souveränität',symbol:'⬡',relevance:90,date:'05.05.2026',description:'Technologische Abhängigkeiten werden zum strategischen Geschäftsrisiko.',insight:'Unternehmen bewerten Cloud, Chips, Modelle und Datenräume zunehmend nach Kontrollierbarkeit und Resilienz – nicht nur nach Preis und Leistung.',stage:'Beschleunigung',horizon:'Jetzt',source:'Technology Trends Report – März 2026',sourceUrl:'https://www.gov.pl/web/national-institute-of-telecommunications/the-future-already-here-just-not-everywhere'},
  {id:'ai-native-work',category:'Business',title:'AI-native Arbeit',symbol:'↗',relevance:93,date:'29.01.2026',description:'Rollen und Prozesse werden von Grund auf für die Zusammenarbeit mit KI gestaltet.',insight:'Der nächste Produktivitätsschub entsteht nicht durch zusätzliche Tools, sondern durch neu geschnittene Verantwortlichkeiten, Lernpfade und Arbeitsabläufe.',stage:'Beschleunigung',horizon:'Jetzt',source:'IEEE: Technology Predictions 2026',sourceUrl:'https://www.computer.org/resources/2026-tech-predictions'},
  {id:'arbeitsmarkt-qualitaet',category:'Gesellschaft',title:'Fragile Arbeitsmärkte',symbol:'≋',relevance:82,date:'14.01.2026',description:'Stabile Beschäftigung verdeckt stagnierende Jobqualität und Ungleichheit.',insight:'Technologischer Wandel und demografischer Druck treffen auf fragile Arbeitsmärkte. Qualifizierung und inklusive Produktivitätsgewinne werden zum gesellschaftlichen Schlüsselthema.',stage:'Etablierung',horizon:'Jetzt',source:'ILO: Employment and Social Trends 2026',sourceUrl:'https://www.ilo.org/publications/flagship-reports/employment-and-social-trends-2026'},
  {id:'digitales-vertrauen',category:'Gesellschaft',title:'Digitales Vertrauen',symbol:'◎',relevance:89,date:'29.01.2026',description:'Nachweisbare Identität und Inhaltsintegrität werden zur Basis digitaler Räume.',insight:'Mit synthetischen Inhalten und autonomen Agenten steigt der Bedarf an Herkunftsnachweisen, resilienter Identität und transparenten Prüfverfahren.',stage:'Beschleunigung',horizon:'Jetzt',source:'IEEE: Technology Predictions 2026',sourceUrl:'https://www.computer.org/resources/2026-tech-predictions'},
  {id:'bio-digitale-gesundheit',category:'Gesellschaft',title:'Bio-digitale Gesundheit',symbol:'⌇',relevance:81,date:'02.04.2026',description:'Adaptive Systeme verbinden biologische Signale mit personalisierten Interventionen.',insight:'Wearables und Bio-AI können Therapien kontinuierlicher anpassen. Datenschutz, klinische Evidenz und fairer Zugang entscheiden über gesellschaftliche Akzeptanz.',stage:'Frühphase',horizon:'3–7 Jahre',source:'U.S. GAO: On the Horizon 2026',sourceUrl:'https://www.gao.gov/products/gao-26-108079'},
  {id:'circular-economy',category:'Nachhaltigkeit',title:'Circular Economy 2.0',symbol:'↻',relevance:91,date:'19.05.2026',description:'Zirkularität wird zum Hebel für Wettbewerbsfähigkeit und Resilienz.',insight:'Kreislaufmodelle reduzieren Rohstoffabhängigkeit und Preisschwankungen. Der Schwerpunkt wandert von Pilotprojekten zu Finanzierung und skalierbarer Infrastruktur.',stage:'Wachstum',horizon:'1–3 Jahre',source:'EEA: Unlocking the circular economy',sourceUrl:'https://www.eea.europa.eu/en/analysis/publications/unlocking-the-circular-economy-investment-needs-barriers-and-enabling-conditions'},
  {id:'produktpaesse',category:'Nachhaltigkeit',title:'Digitale Produktpässe',symbol:'▦',relevance:87,date:'10.07.2026',description:'Interoperable Daten machen Materialien und Lieferketten nachvollziehbar.',insight:'Produktpässe verbinden ESG-Nachweise, Reparierbarkeit und Rückführung. Offene Standards werden entscheidend, damit Daten entlang globaler Lieferketten nutzbar bleiben.',stage:'Wachstum',horizon:'1–3 Jahre',source:'UNECE: ESG Traceability 2026',sourceUrl:'https://unece.org/trade/documents/2026/07/reports/report-team-specialists-environmental-social-and-governance'}
];

const grid=document.querySelector('#trend-grid');const empty=document.querySelector('#empty-state');const search=document.querySelector('#search');const filters=[...document.querySelectorAll('.filter')];let activeFilter='all';
const saved=new Set(JSON.parse(localStorage.getItem('trendselect-saved')||'[]'));
function render(){const query=search.value.trim().toLocaleLowerCase('de');const visible=trends.filter(t=>(activeFilter==='all'||t.category===activeFilter)&&(`${t.title} ${t.description} ${t.category}`.toLocaleLowerCase('de').includes(query)));grid.innerHTML=visible.map(t=>`<article class="trend-card"><div class="card-top"><span class="tag">${t.category}</span><button class="save ${saved.has(t.id)?'active':''}" data-save="${t.id}" type="button" aria-label="${saved.has(t.id)?'Aus Merkliste entfernen':'Trend merken'}" aria-pressed="${saved.has(t.id)}">${saved.has(t.id)?'★':'☆'}</button></div><div class="trend-symbol" aria-hidden="true">${t.symbol}</div><h3>${t.title}</h3><p>${t.description}</p><div class="trend-facts"><span><b>${t.relevance}</b>/100 Relevanz</span><time datetime="${t.date.split('.').reverse().join('-')}">${t.date}</time></div><div class="card-bottom"><span class="momentum">${t.stage}</span><button class="open-card" data-open="${t.id}" type="button" aria-label="Details zu ${t.title}">↗</button></div></article>`).join('');empty.hidden=visible.length!==0}
filters.forEach(button=>button.addEventListener('click',()=>{filters.forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});button.classList.add('active');button.setAttribute('aria-pressed','true');activeFilter=button.dataset.filter;render()}));search.addEventListener('input',render);
grid.addEventListener('click',event=>{const saveButton=event.target.closest('[data-save]');if(saveButton){saved.has(saveButton.dataset.save)?saved.delete(saveButton.dataset.save):saved.add(saveButton.dataset.save);localStorage.setItem('trendselect-saved',JSON.stringify([...saved]));render();return}const openButton=event.target.closest('[data-open]');if(openButton)openTrend(openButton.dataset.open)});
const dialog=document.querySelector('#trend-dialog');function openTrend(id){const t=trends.find(item=>item.id===id);dialog.querySelector('.dialog-category').textContent=t.category;dialog.querySelector('h2').textContent=t.title;dialog.querySelector('.dialog-description').textContent=t.description;dialog.querySelector('.dialog-insight').textContent=t.insight;dialog.querySelector('.dialog-meta').innerHTML=`<span>Relevanz<br>${t.relevance}/100</span><span>Phase<br>${t.stage}</span><span>Horizont<br>${t.horizon}</span><span>Stand<br>${t.date}</span>`;const source=dialog.querySelector('.dialog-source');source.href=t.sourceUrl;source.childNodes[0].textContent=`${t.source} `;dialog.showModal()}
dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('#main-nav');menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});nav.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')});
document.querySelector('#newsletter-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const message=document.querySelector('#form-message');if(!form.checkValidity()){message.textContent='Bitte E-Mail-Adresse und Einwilligung prüfen.';form.reportValidity();return}const endpoint=window.TRENDSELECT_CONFIG?.newsletterEndpoint;if(!endpoint){message.textContent='Der Newsletter-Endpunkt wird vorbereitet. Bitte versuche es später erneut.';return}message.textContent='Anmeldung wird übermittelt …';try{const response=await fetch(endpoint,{method:'POST',headers:{Accept:'application/json'},body:new FormData(form)});const result=await response.json();if(!response.ok||result.success===false)throw new Error('Übermittlung fehlgeschlagen');message.textContent='Danke! Bitte bestätige die Anmeldung über die zugesandte E-Mail.';form.reset()}catch(error){message.textContent='Die Anmeldung konnte nicht übermittelt werden. Bitte versuche es später erneut.'}});
async function loadTrendData(){try{const response=await fetch('data/trends.json',{cache:'no-cache'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const payload=await response.json();if(!Array.isArray(payload.trends)||payload.trends.length<10)throw new Error('Ungültiger Trend-Datensatz');trends=payload.trends;const updated=new Date(payload.updatedAt);document.querySelector('#data-status').textContent=`Automatisch aktualisiert: ${updated.toLocaleDateString('de-DE')} · ${trends.length} Signale · öffentliche Quellen`;render()}catch(error){console.warn('Automatische Trenddaten nicht verfügbar, redaktioneller Stand wird verwendet.',error);render()}}
document.querySelector('#year').textContent=new Date().getFullYear();loadTrendData();
