const trends = [
  {id:'regen-tech',category:'Technologie',title:'Regenerative Technologie',symbol:'◌',momentum:'+84%',description:'Technologien, die Ökosysteme aktiv wiederherstellen.',insight:'Der Fokus verschiebt sich von weniger Schaden zu messbarem positivem Nutzen. Das verändert Produktentwicklung, Energie und Infrastruktur.',stage:'Wachstum',horizon:'2–5 Jahre'},
  {id:'ai-native',category:'Technologie',title:'AI-native Interfaces',symbol:'✦',momentum:'+91%',description:'Software, die sich an Absichten statt Klickpfaden orientiert.',insight:'Interfaces werden dialogischer und kontextbezogener. Erfolgreiche Produkte organisieren Arbeit neu, statt nur bestehende Schritte zu automatisieren.',stage:'Beschleunigung',horizon:'Jetzt'},
  {id:'slow-productivity',category:'Business',title:'Slow Productivity',symbol:'≈',momentum:'+68%',description:'Weniger parallele Arbeit, mehr nachhaltiger Fortschritt.',insight:'Unternehmen messen zunehmend Wirkung statt Aktivität. Das reduziert Kontextwechsel und stärkt die Qualität wissensintensiver Arbeit.',stage:'Etablierung',horizon:'1–3 Jahre'},
  {id:'bio-design',category:'Design',title:'Bio-Design',symbol:'⌁',momentum:'+76%',description:'Materialien und Formen, die mit lebenden Systemen entstehen.',insight:'Myzel, Algen und bakterielle Prozesse werden zu Produktionspartnern. Daraus entstehen kreislauffähige Materialien mit neuen Eigenschaften.',stage:'Frühphase',horizon:'3–7 Jahre'},
  {id:'micro-communities',category:'Lifestyle',title:'Micro Communities',symbol:'◎',momentum:'+62%',description:'Kleine, vertrauensbasierte Netzwerke gewinnen an Bedeutung.',insight:'Menschen suchen digitale und lokale Räume mit hoher Relevanz und echter Zugehörigkeit – als Gegenbewegung zu anonymen Massenplattformen.',stage:'Wachstum',horizon:'1–3 Jahre'},
  {id:'circular-systems',category:'Business',title:'Circular Systems',symbol:'↻',momentum:'+79%',description:'Geschäftsmodelle planen Rückführung und Wiederverwendung mit ein.',insight:'Zirkularität wandert vom Nachhaltigkeitsbericht in den Kern von Produkt, Logistik und Erlösmodell.',stage:'Beschleunigung',horizon:'2–5 Jahre'}
];

const grid=document.querySelector('#trend-grid');const empty=document.querySelector('#empty-state');const search=document.querySelector('#search');const filters=[...document.querySelectorAll('.filter')];let activeFilter='all';
const saved=new Set(JSON.parse(localStorage.getItem('trendselect-saved')||'[]'));
function render(){const query=search.value.trim().toLocaleLowerCase('de');const visible=trends.filter(t=>(activeFilter==='all'||t.category===activeFilter)&&(`${t.title} ${t.description} ${t.category}`.toLocaleLowerCase('de').includes(query)));grid.innerHTML=visible.map(t=>`<article class="trend-card"><div class="card-top"><span class="tag">${t.category}</span><button class="save ${saved.has(t.id)?'active':''}" data-save="${t.id}" type="button" aria-label="${saved.has(t.id)?'Aus Merkliste entfernen':'Trend merken'}" aria-pressed="${saved.has(t.id)}">${saved.has(t.id)?'★':'☆'}</button></div><div class="trend-symbol" aria-hidden="true">${t.symbol}</div><h3>${t.title}</h3><p>${t.description}</p><div class="card-bottom"><span class="momentum">${t.momentum} Momentum</span><button class="open-card" data-open="${t.id}" type="button" aria-label="Details zu ${t.title}">↗</button></div></article>`).join('');empty.hidden=visible.length!==0}
filters.forEach(button=>button.addEventListener('click',()=>{filters.forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});button.classList.add('active');button.setAttribute('aria-pressed','true');activeFilter=button.dataset.filter;render()}));search.addEventListener('input',render);
grid.addEventListener('click',event=>{const saveButton=event.target.closest('[data-save]');if(saveButton){saved.has(saveButton.dataset.save)?saved.delete(saveButton.dataset.save):saved.add(saveButton.dataset.save);localStorage.setItem('trendselect-saved',JSON.stringify([...saved]));render();return}const openButton=event.target.closest('[data-open]');if(openButton)openTrend(openButton.dataset.open)});
const dialog=document.querySelector('#trend-dialog');function openTrend(id){const t=trends.find(item=>item.id===id);dialog.querySelector('.dialog-category').textContent=t.category;dialog.querySelector('h2').textContent=t.title;dialog.querySelector('.dialog-description').textContent=t.description;dialog.querySelector('.dialog-insight').textContent=t.insight;dialog.querySelector('.dialog-meta').innerHTML=`<span>Momentum<br>${t.momentum}</span><span>Phase<br>${t.stage}</span><span>Horizont<br>${t.horizon}</span>`;dialog.showModal()}
dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('#main-nav');menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});nav.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')});
document.querySelector('#newsletter-form').addEventListener('submit',event=>{event.preventDefault();const email=event.currentTarget.email;const message=document.querySelector('#form-message');if(!email.checkValidity()){message.textContent='Bitte gib eine gültige E-Mail-Adresse ein.';email.focus();return}localStorage.setItem('trendselect-newsletter',email.value.trim());message.textContent='Danke! Deine Anmeldung wurde lokal vorgemerkt.';event.currentTarget.reset()});
document.querySelector('#year').textContent=new Date().getFullYear();render();
